* Changelog
** 0.6.0

Breaking change - environment config now takes preference over host
config. Seems that, if an environment is explicitly specified, the
expected behaviour is that the environment config is honoured.

Also, added =#nomad/env-var= reader macro to read a config value from
an environment variable.

Thanks to [[https://github.com/oholworthy][Oliver Holworthy]] for
these suggestions!

** 0.5.1

More helpful error message when a snippet can't be found. No breaking
changes.

** 0.5.0

Minor breaking change - removing the whole =:nomad/environments= map
from the full resulting configuration, in line with =:nomad/hosts=

** 0.4.1

Adding in concept of 'environments'

Minor breaking change - in the config meta-information, =:environment=
now points to the current environment's config, and the old
=:environment= key can now be found under =:location=

** 0.3.3

Handling gracefully when any of the configuration files don't exist.

No breaking changes.

** 0.3.2

Allowed private config in the general section, for private files in a
known, common location.

No breaking changes.

Thanks Michael Jakl!

** 0.3.1

Introduced 'snippets' using the =:nomad/snippets= key and the
=#nomad/snippet= reader macro.

No breaking changes.

** 0.3.0

0.3.0 introduces a rather large breaking change: in the outputted
configuration map, rather than lots of :nomad/* keys, all of the
current host/current instance maps are merged into the main output map.

In general, you should just be able to replace:

- =(get-in (my-config) [:nomad/current-host :x :y])= with =(get-in
  (my-config) [:x :y])=

and

- =(get-in (my-config) [:nomad/current-instance :x :y])= with =(get-in
  (my-config) [:x :y])=

unless you have conflicting key names in your general configuration.

** 0.2.1

Mainly the addition of the private configuration - no breaking changes.

- Allowed users to add =:nomad/private-file= key to host/instance maps
  to specify a private configuration file, which is merged into the
  =:nomad/current-host= and =:nomad/current-instance= maps.
- Added =#nomad/file= reader macro
- Added =:nomad/hostname= and =:nomad/instance= keys to
  =:nomad/current-host= and =:nomad/current-instance= maps
  respectively.

** 0.2.0

0.2.0 has introduced a couple of breaking changes:

- =get-config=, =get-host-config= and =get-instance-config= have been
  removed. Use =defconfig= as described above in place of
  =get-config=; the current host and instance config now live under
  the =:nomad/current-host= and =:nomad/current-instance= keys
  respectively.
- Previously, Nomad expected your configuration file to be in a
  =nomad-config.edn= file at the root of the classpath. You can now
  specify the file or resource (or many, in fact, if you use several
  =defconfig= invocations) for Nomad to use.

** 0.1.0

Initial release
